set_property PACKAGE_PIN Y18 [get_ports clk]

set_property PACKAGE_PIN AA6 [get_ports uart_rxd]
set_property PACKAGE_PIN AB6 [get_ports uart_txd]

set_property PACKAGE_PIN G17 [get_ports {key[0]}]
set_property PACKAGE_PIN G18 [get_ports {key[1]}]
set_property PACKAGE_PIN H5 [get_ports {key[2]}]
set_property PACKAGE_PIN L13 [get_ports {key[3]}]

set_property PACKAGE_PIN AA8 [get_ports {led[0]}]
set_property PACKAGE_PIN AB8 [get_ports {led[1]}]
set_property PACKAGE_PIN Y8 [get_ports {led[2]}]
set_property PACKAGE_PIN R14 [get_ports {led[3]}]

set_property IOSTANDARD LVCMOS33 [get_ports clk]


set_property IOSTANDARD LVCMOS33 [get_ports uart_rxd]
set_property IOSTANDARD LVCMOS33 [get_ports uart_txd]

set_property IOSTANDARD LVCMOS33 [get_ports {key[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {key[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {key[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {key[3]}]

set_property IOSTANDARD LVCMOS33 [get_ports {led[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[3]}]


set_property PACKAGE_PIN V17 [get_ports {inf0[0]}]
set_property PACKAGE_PIN W19 [get_ports {inf0[1]}]
set_property PACKAGE_PIN AA18 [get_ports {inf0[2]}]
set_property PACKAGE_PIN V18 [get_ports {inf0[3]}]
set_property PACKAGE_PIN U17 [get_ports {inf0[4]}]
set_property PACKAGE_PIN U20 [get_ports {inf0[5]}]
set_property PACKAGE_PIN AA19 [get_ports {inf0[6]}]
set_property PACKAGE_PIN AB21 [get_ports {inf0[7]}]
set_property PACKAGE_PIN AA20 [get_ports {inf0[8]}]
set_property PACKAGE_PIN Y21 [get_ports {inf0[9]}]
set_property PACKAGE_PIN W21 [get_ports {inf0[10]}]
set_property PACKAGE_PIN P16 [get_ports {inf0[11]}]
set_property PACKAGE_PIN R18 [get_ports {inf0[12]}]
set_property PACKAGE_PIN T21 [get_ports {inf0[13]}]
set_property PACKAGE_PIN P19 [get_ports {inf0[14]}]
set_property PACKAGE_PIN P15 [get_ports {inf0[15]}]
set_property PACKAGE_PIN N17 [get_ports {inf0[16]}]
set_property PACKAGE_PIN W17 [get_ports {inf0[17]}]
set_property PACKAGE_PIN W20 [get_ports {inf0[18]}]
set_property PACKAGE_PIN AB18 [get_ports {inf0[19]}]
set_property PACKAGE_PIN V19 [get_ports {inf0[20]}]
set_property PACKAGE_PIN U18 [get_ports {inf0[21]}]
set_property PACKAGE_PIN V20 [get_ports {inf0[22]}]
set_property PACKAGE_PIN AB20 [get_ports {inf0[23]}]
set_property PACKAGE_PIN AB22 [get_ports {inf0[24]}]
set_property PACKAGE_PIN AA21 [get_ports {inf0[25]}]
set_property PACKAGE_PIN Y22 [get_ports {inf0[26]}]
set_property PACKAGE_PIN W22 [get_ports {inf0[27]}]
set_property PACKAGE_PIN R17 [get_ports {inf0[28]}]
set_property PACKAGE_PIN T18 [get_ports {inf0[29]}]
set_property PACKAGE_PIN U21 [get_ports {inf0[30]}]
set_property PACKAGE_PIN R19 [get_ports {inf0[31]}]
set_property PACKAGE_PIN R16 [get_ports {inf0[32]}]
set_property PACKAGE_PIN P17 [get_ports {inf0[33]}]

set_property PACKAGE_PIN F3 [get_ports {inf1[0]}]
set_property PACKAGE_PIN E2 [get_ports {inf1[1]}]
set_property PACKAGE_PIN H4 [get_ports {inf1[2]}]
set_property PACKAGE_PIN H3 [get_ports {inf1[3]}]
set_property PACKAGE_PIN K4 [get_ports {inf1[4]}]
set_property PACKAGE_PIN K2 [get_ports {inf1[5]}]
set_property PACKAGE_PIN L3 [get_ports {inf1[6]}]
set_property PACKAGE_PIN M3 [get_ports {inf1[7]}]
set_property PACKAGE_PIN B1 [get_ports {inf1[8]}]
set_property PACKAGE_PIN C2 [get_ports {inf1[9]}]
set_property PACKAGE_PIN E1 [get_ports {inf1[10]}]
set_property PACKAGE_PIN G1 [get_ports {inf1[11]}]
set_property PACKAGE_PIN H2 [get_ports {inf1[12]}]
set_property PACKAGE_PIN K1 [get_ports {inf1[13]}]
set_property PACKAGE_PIN M1 [get_ports {inf1[14]}]
set_property PACKAGE_PIN P2 [get_ports {inf1[15]}]
set_property PACKAGE_PIN R1 [get_ports {inf1[16]}]
set_property PACKAGE_PIN E3 [get_ports {inf1[17]}]
set_property PACKAGE_PIN D2 [get_ports {inf1[18]}]
set_property PACKAGE_PIN G4 [get_ports {inf1[19]}]
set_property PACKAGE_PIN G3 [get_ports {inf1[20]}]
set_property PACKAGE_PIN J4 [get_ports {inf1[21]}]
set_property PACKAGE_PIN J2 [get_ports {inf1[22]}]
set_property PACKAGE_PIN K3 [get_ports {inf1[23]}]
set_property PACKAGE_PIN M2 [get_ports {inf1[24]}]
set_property PACKAGE_PIN A1 [get_ports {inf1[25]}]
set_property PACKAGE_PIN B2 [get_ports {inf1[26]}]
set_property PACKAGE_PIN D1 [get_ports {inf1[27]}]
set_property PACKAGE_PIN F1 [get_ports {inf1[28]}]
set_property PACKAGE_PIN G2 [get_ports {inf1[29]}]
set_property PACKAGE_PIN J1 [get_ports {inf1[30]}]
set_property PACKAGE_PIN L1 [get_ports {inf1[31]}]
set_property PACKAGE_PIN N2 [get_ports {inf1[32]}]
set_property PACKAGE_PIN P1 [get_ports {inf1[33]}]

set_property IOSTANDARD LVCMOS33 [get_ports {inf0[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {inf0[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {inf0[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {inf0[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {inf0[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {inf0[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {inf0[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {inf0[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {inf0[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {inf0[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {inf0[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {inf0[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {inf0[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {inf0[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {inf0[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {inf0[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {inf0[16]}]
set_property IOSTANDARD LVCMOS33 [get_ports {inf0[17]}]
set_property IOSTANDARD LVCMOS33 [get_ports {inf0[18]}]
set_property IOSTANDARD LVCMOS33 [get_ports {inf0[19]}]
set_property IOSTANDARD LVCMOS33 [get_ports {inf0[20]}]
set_property IOSTANDARD LVCMOS33 [get_ports {inf0[21]}]
set_property IOSTANDARD LVCMOS33 [get_ports {inf0[22]}]
set_property IOSTANDARD LVCMOS33 [get_ports {inf0[23]}]
set_property IOSTANDARD LVCMOS33 [get_ports {inf0[24]}]
set_property IOSTANDARD LVCMOS33 [get_ports {inf0[25]}]
set_property IOSTANDARD LVCMOS33 [get_ports {inf0[26]}]
set_property IOSTANDARD LVCMOS33 [get_ports {inf0[27]}]
set_property IOSTANDARD LVCMOS33 [get_ports {inf0[28]}]
set_property IOSTANDARD LVCMOS33 [get_ports {inf0[29]}]
set_property IOSTANDARD LVCMOS33 [get_ports {inf0[30]}]
set_property IOSTANDARD LVCMOS33 [get_ports {inf0[31]}]
set_property IOSTANDARD LVCMOS33 [get_ports {inf0[32]}]
set_property IOSTANDARD LVCMOS33 [get_ports {inf0[33]}]

set_property IOSTANDARD LVCMOS33 [get_ports {inf1[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {inf1[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {inf1[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {inf1[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {inf1[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {inf1[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {inf1[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {inf1[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {inf1[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {inf1[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {inf1[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {inf1[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {inf1[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {inf1[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {inf1[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {inf1[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {inf1[16]}]
set_property IOSTANDARD LVCMOS33 [get_ports {inf1[17]}]
set_property IOSTANDARD LVCMOS33 [get_ports {inf1[18]}]
set_property IOSTANDARD LVCMOS33 [get_ports {inf1[19]}]
set_property IOSTANDARD LVCMOS33 [get_ports {inf1[20]}]
set_property IOSTANDARD LVCMOS33 [get_ports {inf1[21]}]
set_property IOSTANDARD LVCMOS33 [get_ports {inf1[22]}]
set_property IOSTANDARD LVCMOS33 [get_ports {inf1[23]}]
set_property IOSTANDARD LVCMOS33 [get_ports {inf1[24]}]
set_property IOSTANDARD LVCMOS33 [get_ports {inf1[25]}]
set_property IOSTANDARD LVCMOS33 [get_ports {inf1[26]}]
set_property IOSTANDARD LVCMOS33 [get_ports {inf1[27]}]
set_property IOSTANDARD LVCMOS33 [get_ports {inf1[28]}]
set_property IOSTANDARD LVCMOS33 [get_ports {inf1[29]}]
set_property IOSTANDARD LVCMOS33 [get_ports {inf1[30]}]
set_property IOSTANDARD LVCMOS33 [get_ports {inf1[31]}]
set_property IOSTANDARD LVCMOS33 [get_ports {inf1[32]}]
set_property IOSTANDARD LVCMOS33 [get_ports {inf1[33]}]

set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets clk_IBUF_BUFG]

set_property BITSTREAM.CONFIG.CONFIGRATE 33 [current_design]
